### ISSUE TITLE
Drop dimension names.

### ISSUE THREAD

**Issue by hyoklee** [cf-convention/CF-2#7]
CF-1.6 says: "The dimensions of a variable must all have different names."

Why is dimension name (or named dimension) necessary?
Isn't coordinates attribute on dataset sufficient? 

I hope CF-2.0 drops such requirement given that backward compatibility (COARDS) is not an issue.

**Comment by dblodgett-usgs** [comment]
@hyoklee -- I get the sense that this issue is probably not worth continuing to pursue for the latest cf-conventions specification. Do you agree?

**Comment by hyoklee** [comment]
@dblodgett-usgs, I agree since I don't care CF-2.0 any more after @JohnLCaron left Unidata.
